//! Server-side share assets: the deterministic coin identity (friendly name +
//! avatar) ported BYTE-IDENTICAL from `web/core/format.js`, and the 1200x630
//! Open Graph PNG card rendered from an SVG with embedded OFL fonts (the
//! debian-slim runtime ships none).
//!
//! Parity contract: `friendly_name` and `avatar_svg` must produce exactly the
//! strings the frontend produces for the same covenant id — the unit tests at
//! the bottom pin outputs generated by running the actual JS under node.

use anyhow::{Context, Result};

/* ------------------------------------------------------- friendly names */
/* Word lists copied verbatim from web/core/format.js. Do not reorder. */

const ADJECTIVES: [&str; 40] = [
    "brave", "quick", "silent", "gentle", "bold", "clever", "curious", "dizzy",
    "eager", "fierce", "glad", "happy", "humble", "jolly", "keen", "lively",
    "lucky", "mellow", "nimble", "noble", "patient", "playful", "proud", "quiet",
    "rapid", "restless", "shy", "sleepy", "sly", "snappy", "steady", "stubborn",
    "sunny", "swift", "tidy", "tiny", "vivid", "wandering", "wise", "zesty",
];
const COLORS: [&str; 12] = [
    "teal", "amber", "coral", "indigo", "jade", "crimson",
    "cobalt", "olive", "violet", "copper", "pearl", "slate",
];
const ANIMALS: [&str; 40] = [
    "otter", "lynx", "crane", "fox", "owl", "badger", "heron", "marmot",
    "falcon", "tortoise", "hare", "raven", "seal", "ibis", "moth", "newt",
    "panda", "quail", "robin", "stoat", "tapir", "urchin", "vole", "wren",
    "yak", "zebra", "gecko", "dolphin", "ferret", "magpie", "hedgehog", "jackal",
    "kiwi", "lemur", "mole", "narwhal", "osprey", "puffin", "squid", "toad",
];

/// JS: `parseInt(id.slice(i*2, i*2+2), 16)` with NaN -> 0. The slice clamps
/// like JS `String.prototype.slice`, so short ids degrade identically.
fn id_byte(id: &str, i: usize) -> u32 {
    let start = (i * 2).min(id.len());
    let end = (i * 2 + 2).min(id.len());
    u32::from_str_radix(&id[start..end], 16).unwrap_or(0)
}

pub fn friendly_name(id: &str) -> String {
    let adj = ADJECTIVES[((id_byte(id, 0) * 256 + id_byte(id, 1)) % ADJECTIVES.len() as u32) as usize];
    let col = COLORS[((id_byte(id, 2) * 256 + id_byte(id, 3)) % COLORS.len() as u32) as usize];
    let ani = ANIMALS[((id_byte(id, 4) * 256 + id_byte(id, 5)) % ANIMALS.len() as u32) as usize];
    format!("{adj}-{col}-{ani}")
}

/* --------------------------------------------------------------- avatar */

/// JS `x.toFixed(1)` — always one decimal, e.g. "32.0". Rust's `{:.1}` picks
/// the same digit: true round-to-nearest ties need the value to be exactly
/// representable at a .x5 boundary, which for doubles only happens at .25/.75
/// (dyadic), where JS half-up and Rust half-even both land on the .x8/.x3
/// side identically for the multipliers used here (0.65 * 15 = 9.75 -> "9.8"
/// both ways).
fn fixed1(x: f64) -> String {
    format!("{x:.1}")
}

/// JS `+(x).toFixed(1)` interpolated into a template literal: the string is
/// parsed back to a number and printed shortest-round-trip, so "32.0"
/// becomes "32" while "31.5" stays "31.5". Returns the re-parsed double
/// (used by later arithmetic, exactly as in JS) plus the printed form.
fn js_round1(x: f64) -> (f64, String) {
    let s = fixed1(x);
    let n: f64 = s.parse().expect("fixed1 output parses");
    let printed = s.strip_suffix(".0").map(str::to_owned).unwrap_or(s);
    (n, printed)
}

/// The avatar's inner parts, shared by the parity `avatar_svg` and the OG
/// card renderer: (bg fill, ring stroke, shape elements).
pub fn avatar_parts(id: &str) -> (String, String, String) {
    let b = |i: usize| id_byte(id, i);
    let hue = (b(6) * 256 + b(7)) % 360;
    let hue2 = (hue + 60 + (b(8) % 150)) % 360;
    let bg = format!("hsl({hue} 45% 17%)");
    let ring = format!("hsl({hue} 50% 42%)");
    let count = 2 + (b(9) % 2);
    let mut shapes = String::new();
    for k in 0..count {
        let o = (10 + k * 5) as usize; // bytes 10.. / 15.. / 20..
        let kind = b(o) % 5;
        let ang = (b(o + 1) as f64 / 255.0) * std::f64::consts::PI * 2.0;
        let dist = (3 + (b(o + 2) % 11)) as f64; // 3..13 from center
        let (cx, cx_s) = js_round1(32.0 + ang.cos() * dist);
        let (cy, cy_s) = js_round1(32.0 + ang.sin() * dist);
        let s = 8 + (b(o + 3) % 8); // 8..15
        let sf = s as f64;
        let rot = b(o + 4) % 90;
        let col = format!(
            "hsl({} {}% {}%)",
            (hue2 + k * 47) % 360,
            60 + (b(o) % 25),
            58 + (b(o + 1) % 16)
        );
        if kind == 0 {
            shapes.push_str(&format!(
                r#"<circle cx="{cx_s}" cy="{cy_s}" r="{}" fill="{col}" opacity="0.92"/>"#,
                fixed1(sf * 0.72)
            ));
        } else if kind == 1 {
            shapes.push_str(&format!(
                r#"<rect x="{}" y="{}" width="{s}" height="{s}" rx="2" fill="{col}" opacity="0.92" transform="rotate({rot} {cx_s} {cy_s})"/>"#,
                fixed1(cx - sf / 2.0),
                fixed1(cy - sf / 2.0)
            ));
        } else if kind == 2 {
            let h = sf * 0.9;
            let p1 = format!("{cx_s},{}", fixed1(cy - h));
            let p2 = format!("{},{}", fixed1(cx - h * 0.87), fixed1(cy + h * 0.5));
            let p3 = format!("{},{}", fixed1(cx + h * 0.87), fixed1(cy + h * 0.5));
            shapes.push_str(&format!(
                r#"<polygon points="{p1} {p2} {p3}" fill="{col}" opacity="0.92" transform="rotate({rot} {cx_s} {cy_s})"/>"#
            ));
        } else if kind == 3 {
            shapes.push_str(&format!(
                r#"<circle cx="{cx_s}" cy="{cy_s}" r="{}" fill="none" stroke="{col}" stroke-width="3.5" opacity="0.92"/>"#,
                fixed1(sf * 0.65)
            ));
        } else {
            shapes.push_str(&format!(
                r#"<rect x="{}" y="{}" width="{s}" height="{s}" rx="2" fill="{col}" opacity="0.92" transform="rotate(45 {cx_s} {cy_s})"/>"#,
                fixed1(cx - sf / 2.0),
                fixed1(cy - sf / 2.0)
            ));
        }
    }
    (bg, ring, shapes)
}

/// Byte-identical port of `avatarSvg(id, size)` from web/core/format.js.
/// The card itself embeds `avatar_parts` directly; this full-string form
/// exists as the parity surface the tests pin against the JS output.
#[cfg_attr(not(test), allow(dead_code))]
pub fn avatar_svg(id: &str, size: u32) -> String {
    let (bg, ring, shapes) = avatar_parts(id);
    format!(
        r#"<svg class="avatar" viewBox="0 0 64 64" width="{size}" height="{size}" aria-hidden="true" focusable="false"><circle cx="32" cy="32" r="30" fill="{bg}" stroke="{ring}" stroke-width="2.5"/>{shapes}</svg>"#
    )
}

/* ------------------------------------------------------------ formatting */

/// Minimal HTML/attribute escaping (port of `esc` in web/core/format.js).
pub fn esc(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn thousands(n: u64) -> String {
    let s = n.to_string();
    let mut out = String::with_capacity(s.len() + s.len() / 3);
    for (i, c) in s.chars().enumerate() {
        if i > 0 && (s.len() - i) % 3 == 0 {
            out.push(',');
        }
        out.push(c);
    }
    out
}

/// Port of the frontend's `fmtAmount` (web/core/state.js): sompi -> "12,345 KAS".
pub fn fmt_amount(sompi: u64, unit: &str) -> String {
    let kas = sompi as f64 / 1e8;
    let s = if kas >= 1000.0 {
        thousands(kas.round() as u64)
    } else if kas >= 1.0 {
        let whole = kas.floor() as u64;
        let cents = ((kas - whole as f64) * 100.0).round() as u64;
        if cents == 100 {
            format!("{}.00", whole + 1)
        } else {
            format!("{whole}.{cents:02}")
        }
    } else if sompi == 0 {
        "0".to_string()
    } else {
        // up to 4 fraction digits, trailing zeros trimmed (toLocaleString-ish)
        let s = format!("{kas:.4}");
        s.trim_end_matches('0').trim_end_matches('.').to_string()
    };
    format!("{s} {unit}")
}

const MONTHS: [&str; 12] = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

/// ms since epoch -> civil (year, month, day) in UTC, no chrono dependency.
/// Civil-from-days per Howard Hinnant's algorithm.
fn civil_date(ms: u64) -> (i64, i64, i64) {
    let days = (ms / 86_400_000) as i64;
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    (if m <= 2 { y + 1 } else { y }, m, d)
}

/// ms since epoch -> "Mar 3, 2026" (UTC).
pub fn fmt_date(ms: u64) -> String {
    let (y, m, d) = civil_date(ms);
    format!("{} {}, {}", MONTHS[(m - 1) as usize], d, y)
}

/// ms since epoch -> "2026-03-03" (UTC) — the W3C date the sitemap's
/// `<lastmod>` and the Atom feed's day-precision stamps want.
pub fn iso_date(ms: u64) -> String {
    let (y, m, d) = civil_date(ms);
    format!("{y:04}-{m:02}-{d:02}")
}

/* --------------------------------------------------------------- OG card */

/// Everything the card needs, precomputed by the handler.
pub struct CardData {
    pub id: String,
    pub name: String,
    pub alive: bool,
    /// e.g. "12,345 TKAS live" or "retired — nothing left unspent"
    pub balance_line: String,
    /// e.g. "born Mar 3, 2026 · 42 events"
    pub born_line: String,
    /// network label, e.g. "testnet-10"
    pub network: String,
}

/// Build the 1200x630 card SVG. Same visual language as web/og-card.html:
/// #0a100f ground, teal #70c7ba accents, blueprint grid, avatar left.
pub fn card_svg(card: &CardData) -> String {
    let (bg, ring, shapes) = avatar_parts(&card.id);
    let name = esc(&card.name);
    let network = esc(&card.network.to_uppercase());
    let balance = esc(&card.balance_line);
    let born = esc(&card.born_line);
    let (pill_col, pill_label) = if card.alive {
        ("#6fd9a4", "ALIVE")
    } else {
        ("#f2a566", "RETIRED")
    };
    // Fit the name into the ~640px column right of the avatar. Space Grotesk
    // Bold averages ~0.58em advance; names run 12..26 chars.
    let name_size = (640.0 / (0.58 * card.name.len() as f64)).min(84.0);
    let name_size = format!("{name_size:.0}");
    format!(
        r##"<svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
<defs>
<radialGradient id="glow" cx="0.5" cy="-0.19" r="1"><stop offset="0" stop-color="#70c7ba" stop-opacity="0.16"/><stop offset="0.7" stop-color="#70c7ba" stop-opacity="0"/></radialGradient>
<pattern id="bp" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="#70c7ba" stroke-opacity="0.05" stroke-width="1"/></pattern>
<linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></linearGradient>
<mask id="gridmask"><rect width="1200" height="630" fill="url(#fade)"/></mask>
<linearGradient id="sweep" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#70c7ba" stop-opacity="0"/><stop offset="0.5" stop-color="#70c7ba" stop-opacity="0.5"/><stop offset="1" stop-color="#70c7ba" stop-opacity="0"/></linearGradient>
</defs>
<rect width="1200" height="630" fill="#0a100f"/>
<rect width="1200" height="630" fill="url(#bp)" mask="url(#gridmask)"/>
<rect width="1200" height="630" fill="url(#glow)"/>
<rect x="888" y="0" width="1.5" height="340" fill="url(#sweep)"/>
<g transform="translate(72,52)"><circle cx="20" cy="20" r="15" fill="none" stroke="#70c7ba" stroke-width="4.5"/><circle cx="20" cy="20" r="5.5" fill="#70c7ba"/></g>
<text x="126" y="83" font-family="Space Grotesk" font-weight="700" font-size="34" fill="#e9f1ef">kascov</text>
<text x="1128" y="80" text-anchor="end" font-family="JetBrains Mono" font-size="17" letter-spacing="2.4" fill="#8fa19d">KASPA {network}</text>
<g transform="translate(87,180) scale(4.3)"><circle cx="32" cy="32" r="30" fill="{bg}" stroke="{ring}" stroke-width="2.5"/>{shapes}</g>
<g><rect x="452" y="212" width="{pill_w}" height="44" rx="22" fill="none" stroke="{pill_col}" stroke-opacity="0.55" stroke-width="1.5"/><circle cx="478" cy="234" r="5.5" fill="{pill_col}"/><text x="494" y="241" font-family="JetBrains Mono" font-size="19" letter-spacing="2" fill="{pill_col}">{pill_label}</text></g>
<text x="452" y="341" font-family="Space Grotesk" font-weight="700" font-size="{name_size}" letter-spacing="-1" fill="#e9f1ef">{name}</text>
<text x="452" y="404" font-family="JetBrains Mono" font-size="26" fill="#a7b8b4">{balance}</text>
<text x="452" y="448" font-family="JetBrains Mono" font-size="22" fill="#8fa19d">{born}</text>
<text x="72" y="566" font-family="JetBrains Mono" font-size="19" fill="#70c7ba">smart coins on Kaspa L1, watched live</text>
<text x="1128" y="566" text-anchor="end" font-family="JetBrains Mono" font-size="23" fill="#70c7ba">kascov.io</text>
</svg>"##,
        pill_w = 60 + pill_label.len() * 14,
    )
}

/* --------------------------------------------------------- SVG -> PNG */

static FONTDB: std::sync::OnceLock<std::sync::Arc<resvg::usvg::fontdb::Database>> =
    std::sync::OnceLock::new();

fn fontdb() -> std::sync::Arc<resvg::usvg::fontdb::Database> {
    FONTDB
        .get_or_init(|| {
            let mut db = resvg::usvg::fontdb::Database::new();
            db.load_font_data(include_bytes!("../assets/SpaceGrotesk-Bold.ttf").to_vec());
            db.load_font_data(include_bytes!("../assets/JetBrainsMono-Regular.ttf").to_vec());
            std::sync::Arc::new(db)
        })
        .clone()
}

/// Render an SVG string to a PNG at its intrinsic size (the card is 1200x630).
pub fn render_png(svg: &str) -> Result<Vec<u8>> {
    let opt = resvg::usvg::Options {
        fontdb: fontdb(),
        ..Default::default()
    };
    let tree = resvg::usvg::Tree::from_str(svg, &opt).context("parse card svg")?;
    let size = tree.size().to_int_size();
    let mut pixmap = resvg::tiny_skia::Pixmap::new(size.width(), size.height())
        .context("allocate pixmap")?;
    resvg::render(&tree, resvg::tiny_skia::Transform::identity(), &mut pixmap.as_mut());
    pixmap.encode_png().context("encode png")
}

/* ------------------------------------------------------------------ tests */

#[cfg(test)]
mod tests {
    use super::*;

    // Expected values generated by running the REAL frontend code
    // (web/core/format.js) under node for three covenant ids present in the
    // production testnet-10 index. If these fail, the two implementations
    // have drifted — fix the Rust side, never the pins.
    const ID_A: &str = "5c38e33dc778e76e97cc4165bc0537c3db969fa79780add36b545b58b1225089";
    const ID_B: &str = "18079a88a32e4fdcd3107f08cd68f9db26170e95a012ab06077d4862e7fa4f42";
    const ID_C: &str = "b2af1a3f7b5c01dda47a9f935b6b33fcc43849a917be6367051213cb705f52b7";

    #[test]
    fn friendly_name_matches_frontend() {
        assert_eq!(friendly_name(ID_A), "eager-copper-yak");
        assert_eq!(friendly_name(ID_B), "stubborn-violet-moth");
        assert_eq!(friendly_name(ID_C), "quiet-slate-tapir");
    }

    #[test]
    fn avatar_svg_matches_frontend_byte_identical() {
        assert_eq!(
            avatar_svg(ID_A, 64),
            r#"<svg class="avatar" viewBox="0 0 64 64" width="64" height="64" aria-hidden="true" focusable="false"><circle cx="32" cy="32" r="30" fill="hsl(206 45% 17%)" stroke="hsl(206 50% 42%)" stroke-width="2.5"/><circle cx="28.8" cy="34.4" r="9.4" fill="hsl(267 75% 63%)" opacity="0.92"/><circle cx="38.3" cy="24.2" r="10.8" fill="hsl(314 80% 69%)" opacity="0.92"/></svg>"#
        );
        assert_eq!(
            avatar_svg(ID_B, 64),
            r#"<svg class="avatar" viewBox="0 0 64 64" width="64" height="64" aria-hidden="true" focusable="false"><circle cx="32" cy="32" r="30" fill="hsl(284 45% 17%)" stroke="hsl(284 50% 42%)" stroke-width="2.5"/><polygon points="41.8,26.8 35.5,37.6 48.1,37.6" fill="hsl(45 62% 66%)" opacity="0.92" transform="rotate(69 41.8 34)"/><rect x="27.4" y="28.2" width="14" height="14" rx="2" fill="hsl(92 79% 64%)" opacity="0.92" transform="rotate(45 34.4 35.2)"/></svg>"#
        );
        assert_eq!(
            avatar_svg(ID_C, 64),
            r#"<svg class="avatar" viewBox="0 0 64 64" width="64" height="64" aria-hidden="true" focusable="false"><circle cx="32" cy="32" r="30" fill="hsl(117 45% 17%)" stroke="hsl(117 50% 42%)" stroke-width="2.5"/><rect x="21.2" y="23.7" width="11" height="11" rx="2" fill="hsl(191 69% 61%)" opacity="0.92" transform="rotate(45 26.7 29.2)"/><polygon points="32.5,19.9 25.5,32.0 39.5,32.0" fill="hsl(238 62% 62%)" opacity="0.92" transform="rotate(79 32.5 28)"/></svg>"#
        );
    }

    #[test]
    fn avatar_hsl_substrings_from_same_bytes() {
        // ID_A: hue = (b6*256+b7)%360 with b6=0x97, b7=0xcc -> 38860 % 360 = 206
        let (bg, ring, shapes) = avatar_parts(ID_A);
        assert_eq!(bg, "hsl(206 45% 17%)");
        assert_eq!(ring, "hsl(206 50% 42%)");
        assert!(shapes.contains("hsl(267 75% 63%)"));
        assert!(shapes.contains(r#"<circle cx="28.8" cy="34.4" r="9.4""#));
    }

    #[test]
    fn card_renders_png() {
        let card = CardData {
            id: ID_A.to_string(),
            name: friendly_name(ID_A),
            alive: true,
            balance_line: "12,345 TKAS live".to_string(),
            born_line: "born Mar 3, 2026 · 42 events".to_string(),
            network: "testnet-10".to_string(),
        };
        let png = render_png(&card_svg(&card)).expect("render");
        // PNG magic + IHDR dimensions 1200x630
        assert_eq!(&png[..8], b"\x89PNG\r\n\x1a\n");
        assert_eq!(&png[16..20], &1200u32.to_be_bytes());
        assert_eq!(&png[20..24], &630u32.to_be_bytes());
    }

    #[test]
    fn dates_and_amounts() {
        assert_eq!(fmt_date(0), "Jan 1, 1970");
        assert_eq!(fmt_date(1_767_225_600_000), "Jan 1, 2026");
        assert_eq!(fmt_amount(0, "KAS"), "0 KAS");
        assert_eq!(fmt_amount(123_456_789_012, "TKAS"), "1,235 TKAS");
        assert_eq!(fmt_amount(150_000_000, "KAS"), "1.50 KAS");
        assert_eq!(fmt_amount(12_340_000, "KAS"), "0.1234 KAS");
    }
}
